# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5683e93468c82b855e2f3c1a3f05c855a3f8b4d27d9e8981089face15b7b4cf9f399b97da05d3e0cb345239f62029443b95a8510a6862d6e65a21d6b201fe71a

test:
  secret_key_base: 3e82bcbab84c602cbe8c61d97b71d708df217182317b720c717e21f3c2ec1119ddb6e69d79b5134e8411733ee28491b1a9a69380f136e50e7fc2b0bf79161d81

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
